### ISSUE TITLE
Deserialization error

### ISSUE THREAD

**Issue by BlueCat300** [NeonOrbit/Dexplore#3]
An error was found when deserializing method parameters if they include Classes **array**(Class[])

- Target method:
public final void a(Application arg9, String arg10, boolean arg11, Class[] arg12)
.method public final a(Landroid/app/Application;Ljava/lang/String;Z[Ljava/lang/Class;)V
- Serialization result:
`<string name="app_center">m:lx.u.a.k:a:android.app.Application:java.lang.String:boolean:[Ljava.lang.Class;:void</string>`
- Error:
java.lang.IllegalArgumentException at io.github.neonorbit.dexplore.result.MethodData.deserialize(MethodData.java:169)

Deserialization works fine if there is only Ljava.lang.Class but breaks if there are [ and ; in string.

**Comment by NeonOrbit** [comment]
Sorry, I didn't think of that. 
I'll remove the validity check and release a new version.

**Comment by NeonOrbit** [comment]
Fixed (892e2b1) in version `1.4.4`
