### ISSUE TITLE
Search for parameter and return types

### ISSUE THREAD

**Issue by larena1** [NeonOrbit/Dexplore#4]
Would it be possible to also search for parameter and return types of methods?
That could make the results more distinct in cases where the method's references are mostly obfuscated themselves.

**Comment by NeonOrbit** [comment]
You can add parameters, return types, method modifiers, annotations and many more. Check all the available methods of a filter. 
Such as: 
```
MethodFilter methodFilter = new MethodFilter.Builder()
    .setParamList(Arrays.asList(...))
    .setReturnTypes(...)
    .setModifiers(Modifier.PUBLIC)
    .build();
```
Please read [wiki](https://github.com/NeonOrbit/Dexplore/wiki) for detailed explanation.

**Comment by larena1** [comment]
I only used the CLI so far and didn't find it there but that works for me then.

**Comment by NeonOrbit** [comment]
I'll add more cli options in future versions.

**Comment by NeonOrbit** [comment]
Added in the latest [version](https://github.com/NeonOrbit/Dexplore/releases/tag/v1.4.5).
