### ISSUE TITLE
Smali source attribute as criterion for finding classes

### ISSUE THREAD

**Issue by larena1** [NeonOrbit/Dexplore#5]
Smali files can contain the filename they were compiled from in the `.source` attribute. Being able to use that as criterion for finding classes would be a nice addition.

**Comment by NeonOrbit** [comment]
``.source``s are actually class names. If you know  the name of a class, there's no need to find it via any other criteria.

**Comment by larena1** [comment]
Are you sure? I think it's only the source file name like for example `Xyz.kt` but that doesn't necessarily need to match the contained classes' name.

Anyways, in that particular case the class name is obfuscated but the source attribute is preserved and it's quite hard to find the class by other means as there are not really any useful references to it.

**Comment by NeonOrbit** [comment]
Could you give me a sample dex (or apk) file where class names are obfuscated but the source attributes are preserved? I need to test it before implementing this feature.

**Comment by larena1** [comment]
https://weatherandradar.en.uptodown.com/android

**Comment by NeonOrbit** [comment]
If you remember any particular filename (.source attribute), it would be helpful. Anyway I'll look into it, thanks.

**Comment by larena1** [comment]
Cache.java for instance

**Comment by NeonOrbit** [comment]
Added in the latest [version](https://github.com/NeonOrbit/Dexplore/releases/tag/v1.4.5).
