### ISSUE TITLE
ListenableFuture import when importing Dexplore

### ISSUE THREAD

**Issue by DHD2280** [NeonOrbit/Dexplore#7]
Hello.
After importing 
`implementation("io.github.neonorbit:dexplore:1.4.5")`
I can't get com.google.common.util.concurrent.ListenableFuture.

I have a class that extends ListenableWorker using for searching updated of my module.
After importing dexplore I can't get com.google.common.util.concurrent.ListenableFuture.

Is there something that causes conflict?
[This is the project](https://github.com/DHD2280/Oxygen-Customizer)

**Comment by NeonOrbit** [comment]
You can either exclude guava from dexplore:
```
implementation("io.github.neonorbit:dexplore:1.4.5") {
    exclude(group = "com.google.guava")
}
```
Or implement guava in your project: `implementation("com.google.guava:guava:32.1.3-android")`

**Comment by DHD2280** [comment]
Thank you, worked 👍
